# Generated by Django 3.0.4 on 2020-03-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_pessoa_xxx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='xxx',
        ),
    ]
